name: Build grpc wheel on IBMZ

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "linux/s390x"

      - name: Install dependencies and build grpc
        id: build
        run: |
            docker run --rm --platform "linux/s390x"
            --mount "type=bind,src=$(pwd),dst=/build"
            -w "/build" s390x/python:3.9 /bin/bash -ec '
            echo "Building grpc ${{ inputs.release }}";
            apt-get install openssl libssl-dev -y ;
            export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1;
            pip install --upgrade pip;
            pip install --upgrade setuptools;
            GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 pip install grpcio==${{ inputs.release }};
            WHEEL_PATH=$(find /root/.cache/pip/wheels/ -name "grpcio*.whl");
            WHEEL_NAME=$(basename $(find /root/.cache/pip/wheels/ -name "grpcio*.whl"));
            echo $WHEEL_PATH;
            echo $WHEEL_NAME;
            cp $WHEEL_PATH /build/;
            ls /build/;'
            
      - name: Capture the file
        id: capture
        run: |
          WHEEL_PATH=$(find $PWD -name "grpcio*.whl")
          echo "Found $WHEEL_PATH"
          echo "ARTIFACT=$WHEEL_PATH" >> $GITHUB_OUTPUT  
                      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.capture.outputs.ARTIFACT }}
          name: ${{ inputs.release }}
          draft: false
          prerelease: false
