name: Build grpc wheel on IBMZ

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "linux/s390x"

      - name: Install dependencies and build grpc
        id: build
        run: |
            docker run --rm --platform "linux/s390x"
            --mount "type=bind,src=$(pwd),dst=/build"
            -w "/build" s390x/python:3.9 /bin/bash -ec '
            export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1;
            apt-get update -y
            apt-get install -y build-essential libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev tk-dev libffi-dev wget curl git
            #Building grpc
            echo "Building grpc ${{ inputs.release }}"
            pip install --upgrade pip
            apt-get install openssl libssl-dev -y 
            echo "Building grpc ${{ inputs.release }}"
            GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 pip install grpcio==${{ inputs.release }} 
            WHEEL_PATH=$(find /root/.cache/pip/wheels/ -name "grpcio*.whl")
            WHEEL_NAME=$(basename $(find /root/.cache/pip/wheels/ -name "grpcio*.whl"))
            echo $WHEEL_PATH
            echo $WHEEL_NAME
            cp $WHEEL_PATH /artifacts/$WHEEL_NAME
            ls /artifacts/'            
                      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./artifacts/grpcio-${{ inputs.release }}-cp39-cp39-linux_s390x.whl
          name: ${{ inputs.release }}
          draft: false
          prerelease: false
